build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base:3.19"
  amd64: "ghcr.io/home-assistant/amd64-base:3.19"
labels:
  org.opencontainers.image.title: "LibreChat"
  org.opencontainers.image.description: "Clone amélioré de ChatGPT avec support multi-modèles IA"
  org.opencontainers.image.source: "https://github.com/AxelPilop/home-assistant-addons"
  org.opencontainers.image.licenses: "MIT"
args:
  LIBRECHAT_VERSION: "main" 