---
name: LibreChat
version: "1.0.0"
slug: librechat
description: Interface de chat IA avec support multi-modèles - LibreChat
url: https://github.com/axel-vair/home-assistant-addons/tree/main/librechat
arch:
  - aarch64
  - amd64
init: false
host_network: true
map:
  - "share:rw"
ports:
  3080/tcp: 3080
ports_description:
  3080/tcp: Interface web LibreChat
webui: http://[HOST]:[PORT:3080]
options:
  mongodb_url: ""
  jwt_secret: ""
  openai_api_key: ""
  anthropic_api_key: ""
  google_api_key: ""
  debug_logging: false
schema:
  mongodb_url: "str?"
  jwt_secret: "str?"
  openai_api_key: "str?"
  anthropic_api_key: "str?"
  google_api_key: "str?"
  debug_logging: bool
startup: application
backup: hot 