name: LibreChat
version: v0.7.7
slug: librechat
description: Clone amélioré de ChatGPT avec support multi-modèles IA (OpenAI, Anthropic, Google, etc.)
arch:
  - armv7
  - aarch64
  - amd64
image: ghcr.io/danny-avila/librechat:latest
init: false
ports:
  3080/tcp: 3080
ports_description:
  3080/tcp: Interface Web LibreChat
environment:
  HOST: "0.0.0.0"
  PORT: "3080"
  MONGO_URI: "mongodb://mongo:27017/LibreChat"
  DOMAIN_CLIENT: "http://localhost:3080"
  DOMAIN_SERVER: "http://localhost:3080"
services:
  - mongodb
map:
  - config:rw
  - share:rw
options:
  mongo_initdb_root_username: librechat
  mongo_initdb_root_password: password
  debug_logging: false
  check_balance: false
  jwt_secret: !secret librechat_jwt_secret
  jwt_refresh_secret: !secret librechat_jwt_refresh_secret
  creds_key: !secret librechat_creds_key
  creds_iv: !secret librechat_creds_iv
schema:
  mongo_initdb_root_username:
    type: str
    required: false
  mongo_initdb_root_password:
    type: password
    required: false
  debug_logging:
    type: bool
    required: false
  check_balance:
    type: bool
    required: false
  jwt_secret:
    type: password
    required: false
  jwt_refresh_secret:
    type: password
    required: false
  creds_key:
    type: password
    required: false
  creds_iv:
    type: password
    required: false
url: https://github.com/danny-avila/LibreChat
webui: http://[HOST]:[PORT:3080] 