ARG BUILD_FROM
FROM ghcr.io/danny-avila/librechat:latest

# Labels pour Home Assistant Supervisor
LABEL \
  io.hass.version="1.0.0" \
  io.hass.type="addon" \
  io.hass.arch="aarch64|amd64"

# Exposition du port
EXPOSE 3080 